- name: Install jmespath
  become: yes
  package:
    name: python3-jmespath
    state: present
  
# - name: Install python3-docker
#   become: yes
#   package:
#     name:   python3-docker
#     state: present

